# Generated by Django 3.0.2 on 2020-02-04 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homepage',
            new_name='Router',
        ),
    ]
