# Generated by Django 3.0.2 on 2020-02-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('app_version', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
