# Generated by Django 3.0.2 on 2020-02-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='docker_image',
            field=models.FileField(default='NULL', upload_to='docker_images/'),
            preserve_default=False,
        ),
    ]
